# Generated by Django 4.0.6 on 2022-08-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app77user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForexDen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Balance', models.CharField(max_length=10)),
                ('Earning', models.CharField(max_length=10)),
                ('Lase_Deposit', models.CharField(max_length=10)),
                ('Pending_Withdrawal', models.CharField(max_length=10)),
                ('Referals', models.CharField(max_length=3)),
                ('Earned_Commission', models.CharField(max_length=10)),
            ],
        ),
    ]
