# Generated by Django 4.0.6 on 2022-08-29 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app77user', '0003_rename_lase_deposit_forexden_last_deposit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ForexDen',
            new_name='ForexDenModel',
        ),
    ]
