# Generated by Django 4.0.6 on 2022-08-30 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app77user', '0005_delete_forexdenmodel_customuser_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForexDenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Balance', models.CharField(max_length=10)),
                ('Earning', models.CharField(max_length=10)),
                ('Last_Deposit', models.CharField(max_length=10)),
                ('Pending_Withdrawal', models.CharField(max_length=10)),
                ('Referals', models.CharField(max_length=3)),
                ('Earned_Commission', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='Balance',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='Earned_Commission',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='Earning',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='Last_Deposit',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='Pending_Withdrawal',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='Referals',
        ),
    ]
